name: refresh-data
on:
  schedule:
    - cron:  "30 10 * * *"   # 06:30 America/New_York
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --no-cache-dir -r requirements.txt

      - name: Validate catalog
        run: |
          python -m pip install jsonschema
          python -m jsonschema -i csv_catalog.json schema.json

      - name: Run ETL
        run: python etl.py

      - name: Commit & push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): nightly refresh"
          file_pattern: docs/inventory.json